name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main # Workflow akan jalan otomatis setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate Clasp
        env:
            CLASP_TOKEN: ${{ secrets.CLASPRC_JSON }}
        run: echo "$CLASP_TOKEN" > ~/.clasprc.json

      - name: Push to GAS
        run: clasp push -f